### PR TITLE
AV-1578: Update for guide menu previous and next buttons

### PR DESCRIPTION
**Pull request by dvainio**
Update some of the selectors and the urls since they had
changed in a previous update.

Refs AV-1578

### CODE REVIEW

**Review by beazil — CHANGES_REQUESTED** [review]
Functionality works basically, but looks like design differs from actual implementation. In design there isn't different buttons for next and previous, instead they are links in same container that has blue background. Also next/previous is hidden when active page is last or first  in menu. So I would say that this needs fixing.

**Review by beazil — COMMENTED** [review]
Now it looks great. I would approve it, but there was still one fix about that subnav-items (aka. anchor links) should be ignored in next-button

**Comment by dvainio** [comment]
Screenshot 2022-02-25 at 14 46 05

**Review by Zharktas — APPROVED** [review]

**Pull request merged**
